# I have prepared this notebook on classification dataset. In case of regression I there is only change of one hyperparameter 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

In [2]:
data = pd.read_csv(r'D:\Datasets\glass.csv')
data.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
data.shape

(214, 10)

In [4]:
data.size

2140

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [6]:
data['Type'].value_counts()

2    76
1    70
7    29
3    17
5    13
6     9
Name: Type, dtype: int64

In [7]:
data['Type'] = np.where(data['Type']<3,0,1)
data['Type'].value_counts()

0    146
1     68
Name: Type, dtype: int64

In [8]:
x = data.drop('Type',axis=1)
y = data['Type']

In [9]:
from imblearn.over_sampling import SMOTE
s = SMOTE()
x, y = s.fit_resample(x,y)
print(x.shape, y.shape)

(292, 9) (292,)


In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=101)

In [11]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [12]:
y_pred = rfc.predict(x_test)

In [13]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred))
print(metrics.confusion_matrix(y_test,y_pred))
print(metrics.classification_report(y_test,y_pred))

0.8904109589041096
[[32  2]
 [ 6 33]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.89        34
           1       0.94      0.85      0.89        39

    accuracy                           0.89        73
   macro avg       0.89      0.89      0.89        73
weighted avg       0.90      0.89      0.89        73



In [14]:
rfc.score(x_train,y_train)

1.0

# Manual HyperParameter Tuning

#### To view how the min_samples_split, max_depth, min_samples_leaf works view 'View for Better Understanding' notebook

### 1 - n_estimators - (default=100)

In [15]:
rfc1 = RandomForestClassifier(n_estimators=500) 
rfc1.fit(x_train,y_train)

RandomForestClassifier(n_estimators=500)

In [16]:
y_pred1 = rfc1.predict(x_test)

In [17]:
print(metrics.accuracy_score(y_test,y_pred1))
print(metrics.confusion_matrix(y_test,y_pred1))
print(metrics.classification_report(y_test,y_pred1))

0.8904109589041096
[[32  2]
 [ 6 33]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.89        34
           1       0.94      0.85      0.89        39

    accuracy                           0.89        73
   macro avg       0.89      0.89      0.89        73
weighted avg       0.90      0.89      0.89        73



In [18]:
rfc1.score(x_train,y_train)

1.0

## 2 - Criterion - (default="gini")

In [19]:
rfc2 = RandomForestClassifier(criterion="entropy") 
rfc2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy')

In [20]:
y_pred2 = rfc2.predict(x_test)

In [21]:
print(metrics.accuracy_score(y_test,y_pred2))
print(metrics.confusion_matrix(y_test,y_pred2))
print(metrics.classification_report(y_test,y_pred2))

0.8904109589041096
[[32  2]
 [ 6 33]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.89        34
           1       0.94      0.85      0.89        39

    accuracy                           0.89        73
   macro avg       0.89      0.89      0.89        73
weighted avg       0.90      0.89      0.89        73



In [22]:
rfc1.score(x_train,y_train)

1.0

## 3 - max_depth - (default=None)

In [23]:
rfc3 = RandomForestClassifier(max_depth=3) 
rfc3.fit(x_train,y_train)

RandomForestClassifier(max_depth=3)

In [24]:
y_pred3 = rfc3.predict(x_test)

In [25]:
print(metrics.accuracy_score(y_test,y_pred3))
print(metrics.confusion_matrix(y_test,y_pred3))
print(metrics.classification_report(y_test,y_pred3))

0.863013698630137
[[32  2]
 [ 8 31]]
              precision    recall  f1-score   support

           0       0.80      0.94      0.86        34
           1       0.94      0.79      0.86        39

    accuracy                           0.86        73
   macro avg       0.87      0.87      0.86        73
weighted avg       0.87      0.86      0.86        73



In [26]:
rfc3.score(x_train,y_train)

0.867579908675799

## 4 - min_samples_split - (default=2)

In [27]:
rfc4 = RandomForestClassifier(min_samples_split=10)
rfc4.fit(x_train,y_train)

RandomForestClassifier(min_samples_split=10)

In [28]:
y_pred4 = rfc4.predict(x_test)

In [29]:
print(metrics.accuracy_score(y_test,y_pred4))
print(metrics.confusion_matrix(y_test,y_pred4))
print(metrics.classification_report(y_test,y_pred4))

0.8904109589041096
[[32  2]
 [ 6 33]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.89        34
           1       0.94      0.85      0.89        39

    accuracy                           0.89        73
   macro avg       0.89      0.89      0.89        73
weighted avg       0.90      0.89      0.89        73



In [30]:
rfc4.score(x_train,y_train)

0.9726027397260274

## 5 - min_samples_leaf - (default=1)

In [31]:
rfc5 = RandomForestClassifier(min_samples_leaf=5)
rfc5.fit(x_train,y_train)

RandomForestClassifier(min_samples_leaf=5)

In [32]:
y_pred5 = rfc5.predict(x_test)

In [33]:
print(metrics.accuracy_score(y_test,y_pred5))
print(metrics.confusion_matrix(y_test,y_pred5))
print(metrics.classification_report(y_test,y_pred5))

0.8767123287671232
[[32  2]
 [ 7 32]]
              precision    recall  f1-score   support

           0       0.82      0.94      0.88        34
           1       0.94      0.82      0.88        39

    accuracy                           0.88        73
   macro avg       0.88      0.88      0.88        73
weighted avg       0.88      0.88      0.88        73



In [34]:
rfc5.score(x_train,y_train)

0.9315068493150684

## 6 - max_features - (default="sqrt") (for versions <1.1 default="auto")

### although, auto is same as sqrt

In [35]:
rfc6 = RandomForestClassifier(max_features="log2")
rfc6.fit(x_train,y_train)

RandomForestClassifier(max_features='log2')

In [36]:
y_pred6 = rfc6.predict(x_test)

In [37]:
print(metrics.accuracy_score(y_test,y_pred6))
print(metrics.confusion_matrix(y_test,y_pred6))
print(metrics.classification_report(y_test,y_pred6))

0.8767123287671232
[[32  2]
 [ 7 32]]
              precision    recall  f1-score   support

           0       0.82      0.94      0.88        34
           1       0.94      0.82      0.88        39

    accuracy                           0.88        73
   macro avg       0.88      0.88      0.88        73
weighted avg       0.88      0.88      0.88        73



In [38]:
rfc6.score(x_train,y_train)

1.0

## 7 - max_samples - (default=None) 

### (can only be used if bootstrap=True) In Random Forest bootstrap is always set as True

In [39]:
rfc7 = RandomForestClassifier(max_samples=150)
rfc7.fit(x_train,y_train)

RandomForestClassifier(max_samples=150)

In [40]:
y_pred7 = rfc7.predict(x_test)

In [41]:
print(metrics.accuracy_score(y_test,y_pred7))
print(metrics.confusion_matrix(y_test,y_pred7))
print(metrics.classification_report(y_test,y_pred7))

0.8904109589041096
[[32  2]
 [ 6 33]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.89        34
           1       0.94      0.85      0.89        39

    accuracy                           0.89        73
   macro avg       0.89      0.89      0.89        73
weighted avg       0.90      0.89      0.89        73



In [42]:
rfc7.score(x_train,y_train)

1.0

# HyperParamter Tuning using RandomizedSearchCV

In [43]:
from sklearn.model_selection import RandomizedSearchCV


In [44]:
params = {
    'n_estimators':[int(i) for i in range(0,1000,50)],
    'criterion':['gini','entropy','log_loss'],
    'max_depth':[int(i) for i in range(1,50,1)],
    'min_samples_split':[int(i) for i in range(2,50,1)],
    'min_samples_leaf':[int(i) for i in range(1,50,1)],
    'max_features':['sqrt','log2',None],
    'max_samples':[int(i) for i in range(0,219,3)]
}

In [45]:
rfclf = RandomForestClassifier()
random_cv_rfclf = RandomizedSearchCV(estimator = rfclf , param_distributions=params , n_iter = 100 , cv = 5 , n_jobs = 7,verbose=True)
random_cv_rfclf.fit(x_train,y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


[Parallel(n_jobs=7)]: Using backend LokyBackend with 7 concurrent workers.
[Parallel(n_jobs=7)]: Done  36 tasks      | elapsed:    4.4s
[Parallel(n_jobs=7)]: Done 186 tasks      | elapsed:   15.6s
[Parallel(n_jobs=7)]: Done 461 tasks      | elapsed:   33.4s
[Parallel(n_jobs=7)]: Done 500 out of 500 | elapsed:   37.9s finished


RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=7,
                   param_distributions={'criterion': ['gini', 'entropy',
                                                      'log_loss'],
                                        'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                      10, 11, 12, 13, 14, 15,
                                                      16, 17, 18, 19, 20, 21,
                                                      22, 23, 24, 25, 26, 27,
                                                      28, 29, 30, ...],
                                        'max_features': ['sqrt', 'log2', None],
                                        'max_samples': [0, 3, 6, 9, 12, 15, 18,
                                                        21, 24, 27, 30, 33, 36,
                                                        39, 42, 45, 48, 51, 54,
                                                   

In [46]:
best_params = random_cv_rfclf.best_estimator_
best_params

RandomForestClassifier(max_depth=19, max_features=None, max_samples=153,
                       min_samples_leaf=3, min_samples_split=11,
                       n_estimators=250)

In [47]:
rfc_final = max_depth=19, max_features=None, max_samples=153,
                       min_samples_leaf=3, min_samples_split=11,
                       n_estimators=250
rfc_final.fit(x_train,y_train)

In [48]:
# y_pr = rfc_final.predict(x_test)

In [49]:
# print(metrics.accuracy_score(y_test,y_pr))
# print(metrics.confusion_matrix(y_test,y_pr))
# print(metrics.classification_report(y_test,y_pr))

In [50]:
# print(rfc_final.score(x_train,y_train))